TICKERS = [
    "AAPL", "MSFT", "GOOGL", "AMZN", "TSLA", "META", "NVDA", "JPM", "V", "MA",
    "PYPL", "DIS", "NFLX", "ADBE", "CRM", "INTC", "CSCO", "ORCL", "IBM", "QCOM",
    "TXN", "AVGO", "AMD", "BIDU", "UBER", "SNAP", "TWTR", "SQ", "ZM", "SHOP",
    "SPOT", "BYND", "ZM", "DOCU", "WORK", "ROKU", "EA", "ATVI", "LULU", "NKE",
    "SBUX", "MCD", "KO", "PEP", "PM", "MO", "CVX", "XOM", "COP", "BP",
    "TOT", "RDS.A", "BP", "SLB", "HAL", "CAT", "DE", "GE", "BA", "LMT",
    "GD", "NOC", "HUM", "UNH", "JNJ", "PFE", "MRK", "ABBV", "LLY", "BMY",
    "GILD", "REGN", "VRTX", "BIIB", "AMGN", "CELG", "MDT", "SYK", "DHR", "BDX",
    "ZTS", "ISRG", "COST", "WMT", "TGT", "HD", "LOW", "TJX", "KR", "M",
    "DLTR", "DG", "ROST", "KMX", "F", "GM", "TM", "HMC", "TSM", "ASML",
    "ADSK", "NOW", "WDAY", "PANW", "FTNT", "ZM", "DOCU", "OKTA", "NET", "DDOG",
    "MDB", "CRWD", "ZS", "TEAM", "SNOW", "TWLO", "LYFT", "UBER", "ETSY", "EBAY",
    "VZ", "T", "TMUS", "S", "CMCSA", "DISCA", "DISH", "CHTR", "FOXA", "FOX",
    "NLSN", "CBS", "VIAC", "IPG", "OMC", "WU", "PYPL", "SQ", "AXP", "COF",
    "DFS", "SYF", "BAC", "WFC", "C", "GS", "MS", "JPM", "BLK", "TROW",
    "IVZ", "MET", "PRU", "ALL", "AIG", "HIG", "TRV", "PGR", "LNC", "CINF",
    "CB", "MMC", "WRB", "RE", "CME", "ICE", "NDAQ", "SCHW", "MCO", "SPGI",
    "MSCI", "VICI", "O", "EQR", "PLD", "PSA", "AVB", "ESS", "MAA", "UDR",
    "AMT", "CCI", "WY", "DHI", "LEN", "PHM", "KBH", "NVR", "LHX", "LMT",
    "RTN", "BA", "GD", "NOC", "TXT", "COL", "AJRD", "TDY", "FLIR", "HII",
    "IT", "JCI", "PH", "PNR", "ROK", "SWK", "ECL", "BLL", "LIN", "APD",
    "SHW", "VMC", "DD", "SEE", "OLN", "LYB", "IFF", "CE", "EMN", "PKG",
    "WRK", "AVY", "BLL", "PPG", "FLS", "CF", "MOS", "NEM", "GOLD", "AU",
    "AG", "PAAS", "KGC", "HL", "FNV", "EGO", "RGLD", "BTG", "BHP", "RIO",
    "VALE", "FCX", "SCCO", "NUE", "X", "CLF", "HMY", "MGM", "WYNN", "LVS",
    "CZR", "MRO", "EOG", "APA", "DVN", "PXD", "CXO", "MPC", "PSX", "VLO",
    "HES", "OXY", "COP", "XOM", "CVX", "BP", "TOT", "RDS.A", "BP",
    "BTC-USD", "ETH-USD", "ADA-USD", "BNB-USD", "XRP-USD", "DOGE-USD", "SOL-USD"
]
